spring:
  mail:
    host: smtp.163.com
    port: 465
    username: a1013630965@163.com
# 使用 jasypt 加密密码，使用com.xkcoding.email.PasswordTest.testGeneratePassword 生成加密密码，替换 ENC(加密密码)
    password: ENC(NHBRVYAkbigqWtfMKSYJdQ==)
    protocol: smtp
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: demo-email
# 为 jasypt 配置解密秘钥
jasypt:
  encryptor:
    password: demo-email